# Metadata about this component, to be used in the CMS
spec:
  structures: []
  label: Tag
  description: A tag subcomponent
  icon: smart_button
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  text: "Tag"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
